language: csharp
solution: Terminal.sln
install:
  - dotnet nuget locals http-cache --clear
script:
  - tsh_version=1.4.0-pre1
  - msbuild /t:Restore $TRAVIS_BUILD_DIR/Terminal.sln
  - cd $TRAVIS_BUILD_DIR/
  - msbuild /p:Configuration=Release Terminal.sln
mono: "6.8.0"
dotnet: "3.1.201"
os: "osx"
